---
- name: Deploy Scientific Calculator Docker Container
  hosts: docker_hosts
  become: yes 

  tasks:
    # Task 1
    - name: Ensure docker.io is installed
      ansible.builtin.package:
        name: docker.io
        state: present
    
    # Task 2: Pull the latest Docker image 
    - name: Pull the latest calculator image
      community.docker.docker_image:
        name: "{{ DOCKER_IMAGE }}"
        source: pull
        state: present

    # Task 3
    - name: Run the new calculator container
      community.docker.docker_container:
        name: scientific_calculator_container
        image: "{{ DOCKER_IMAGE }}"
        # ports:
        #   - "8080:8080"
        state: started
        restart_policy: always
        recreate: yes 